spring:
  application:
    name: chat-service
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}
#      database: ${MONGODB_DATABASE}
#      username: ${MONGODB_USERNAME}
#      password: ${MONGODB_PASSWORD}
#      auto-index-creation: true
logging:
  level:
    org:
      springframework:
        data:
          mongodb: debug

